services:
    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_EXTRA_DIRECTIVES: 'cors_origins http://localhost:8000'
        networks:
            - symfony
        command: /usr/bin/caddy run --config /etc/caddy/Caddyfile
        ports:
            - "9999:80"
        volumes:
            - caddy_data:/data
            - caddy_config:/config
            - ./infra/caddy/:/etc/caddy/

volumes:
  caddy_data:
  caddy_config:

networks:
  symfony:
    name: symfony
